update build workflows

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,7 +4,6 @@ on:
   push:
     branches:
       - master
-      - dev
 
 permissions:
   contents: write
@@ -49,7 +48,25 @@ jobs:
 
           D8_PATH=$(find "$SDK_ROOT/build-tools" -name d8 | sort -V | tail -n 1)
           AIDL_PATH=$(find "$SDK_ROOT/build-tools" -name aidl | sort -V | tail -n 1)
-          R8_PATH=$(find "$SDK_ROOT" -name r8.jar | head -n 1)
+
+          curl -L \
+            https://storage.googleapis.com/r8-releases/raw/8.4.46/r8lib.jar \
+            -o r8.jar
+
+          cat > r8 << 'EOF'
+          #!/usr/bin/env bash
+
+          HERE="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
+
+          exec java \
+            -cp "$HERE/r8.jar" \
+            com.android.tools.r8.R8 \
+            "$@"
+          EOF
+
+          chmod +x r8
+
+          R8_PATH="$(pwd)/r8"
 
           [ -n "$D8_PATH" ]   || { echo "d8 not found"; exit 1; }
           [ -n "$AIDL_PATH" ] || { echo "aidl not found"; exit 1; }
@@ -59,8 +76,8 @@ jobs:
           sed -i "s|^MINIFIED=.*|MINIFIED=${{ matrix.minified }}|" config.sh
 
           if [ "${{ matrix.minified }}" = "true" ]; then
-            [ -n "$R8_PATH" ] || { echo "r8.jar not found"; exit 1; }
-            sed -i "s|^R8=.*|R8=java -jar $R8_PATH|" config.sh
+            [ -x "$R8_PATH" ] || { echo "r8 executable not found"; exit 1; }
+            sed -i "s|^R8=.*|R8=$R8_PATH|" config.sh
           fi
 
       - name: Build
